# Generated by Django 3.1.7 on 2021-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='user tag icon binary'),
        ),
    ]
