# Generated by Django 3.1.7 on 2021-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210308_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='user tag name')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='user tag icon binary')),
            ],
            options={
                'verbose_name': 'default_tag',
                'verbose_name_plural': 'default_tags',
                'db_table': 'default_tag',
            },
        ),
    ]
