# Generated by Django 3.1.7 on 2021-03-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_defaulttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], max_length=7, unique=True, verbose_name='transation type')),
            ],
            options={
                'verbose_name': 'transaction_type',
                'verbose_name_plural': 'transaction_types',
                'db_table': 'transaction_type',
            },
        ),
        migrations.AlterField(
            model_name='defaulttag',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='user tag name'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='user tag name'),
        ),
    ]
