# Generated by Django 3.1.7 on 2021-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210308_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='transaction amount')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='transaction datetime')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transaction',
            },
        ),
    ]
