# Generated by Django 3.1.7 on 2021-03-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='default_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.defaulttag'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.usertag'),
        ),
    ]
