# Generated by Django 3.1.7 on 2021-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=7, unique=True, verbose_name='frequency')),
            ],
            options={
                'verbose_name': 'scheduled_frequency',
                'verbose_name_plural': 'scheduled_frequencies',
                'db_table': 'scheduled_frequency',
            },
        ),
    ]
