# Generated by Django 3.1.7 on 2021-03-09 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0008_scheduledfrequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('scheduled_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.scheduledfrequency')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scheduled_transaction',
                'verbose_name_plural': 'scheduled_transactions',
                'db_table': 'scheduled_transaction',
            },
        ),
    ]
